"""empty message

Revision ID: 365f306a9989
Revises: 476d45a0afdd
Create Date: 2022-06-22 12:57:05.714284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365f306a9989'
down_revision = '476d45a0afdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['password_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
